name: Cache and install dependency
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache-deps
      with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json')}}

    - name: Install dependencies
      run: npm ci
      shell: bash
