name: Build Test and Deploy App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json')}}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.collect_script.outputs.script_file }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json')}}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Output script file
        id: collect_script
        run: |
          SCRIPT_FILE=$(find dist/assets/ -name "*.js" -type f -execdir echo {} \;)
          echo "script_file=$SCRIPT_FILE" >> "$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: dist-files
            path: dist

  deploy:
      needs: build
      runs-on: ubuntu-latest
            
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
      
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'

        - name: Cache dependencies
          uses: actions/cache@v4
          id: cache-deps
          with:
            path: ~/.npm
            key: npm-${{ hashFiles('package-lock.json')}}

        - name: Install dependencies
          if: steps.cache-deps.outputs.cache-hit != 'true'
          run: npm ci

        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
              name: dist-files
        
        - name: Get script file output
          run: echo "Script file - ${{ needs.build.outputs.script-file }}"
          
        # Placeholder for deployment
        - name: Deploy app
          run: echo Deployment successfull!
  
  report-failure:
      needs: [deploy]
      runs-on: ubuntu-latest
      if: failure()

      steps:
        - name: Check if a job failed
          run: echo "Something went wrong"
