name: Sample workflow for issues
on:
    issues:
        types: [opened, edited, deleted, closed]
jobs:
    sample-job:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "{{ toJSON(github) }}"
